# Generated by Django 2.0.7 on 2018-07-24 09:55

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('hotelbooking', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bookings',
            new_name='Booking',
        ),
        migrations.RenameModel(
            old_name='RoomTypes',
            new_name='RoomType',
        ),
    ]
