# Generated by Django 2.0.7 on 2018-07-26 21:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hotelbooking', '0003_auto_20180726_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='createdAt',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='updatedAT',
        ),
        migrations.RemoveField(
            model_name='history',
            name='createdAt',
        ),
        migrations.RemoveField(
            model_name='history',
            name='updatedAT',
        ),
        migrations.AddField(
            model_name='booking',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='last_modified',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='last_modified',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='last_modified',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomtype',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomtype',
            name='last_modified',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
    ]
