# Generated by Django 2.0.7 on 2018-09-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelbooking', '0003_roomtype_fully_booked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomtype',
            old_name='count',
            new_name='booking_count',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='fully_booked',
        ),
        migrations.AddField(
            model_name='roomtype',
            name='room_count',
            field=models.IntegerField(default=0),
        ),
    ]
