# Generated by Django 2.0.7 on 2018-09-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelbooking', '0005_auto_20180909_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='available_count',
            field=models.IntegerField(default=-1),
        ),
    ]
